#! /bin/sh
# /*@@
#   @file    freebsd
#   @date    Tue 20 Jan 2004
#   @author  Thomas Radke
#   @desc
#            generic known-architectures file for all versions of FreeBSD
#   @enddesc
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/freebsd,v 1.1 2004-01-20 13:08:10 tradke Exp $
# @@*/

#CCTK ARCHITECTURE freebsd[1-9]*

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  # Fortran code needs g2c library
  : ${LIBS='g2c m'}

  ARFLAGS=-ruc
  USE_RANLIB=yes
  RANLIBFLAGS=

  # MPI stuff
  #
  # FreeBSD has no native MPI, so we don't set any NATIVE_MPI_XXX variables.
  # This is caught by lib/make/extras/MPI/NATIVE then.

fi
