#include "thornlist.hh"

namespace Formaline {

namespace ThornList {

// This header file is automatically generated by the flesh.
// It defines
//    static char const * const thorn_name[];
//    static int const nthorns;
#include "thornlist.h"

char const *const *ThornNames() { return thorn_name; }

int NumThorns() { return nthorns; }

} // namespace ThornList

} // namespace Formaline
