#! /bin/sh

if [ ! -n "$1" ]
then
  figpath="."
else
 figpath=$1
fi

files=`find ${figpath} -type f -name "*.pdf"`

if [ -n "${files}" ]; then
  echo "  Converting figures to postscript"
fi

for i in $files; do
  epsfilename=`echo $i | sed s/.pdf$/.eps/`
  if [ "$i" != "documentation.pdf" ] && [ ! -e $epsfilename ]; then
    echo "   " `basename $i` " -> " `basename $epsfilename`
    pdf2ps $i $epsfilename
  fi
done
