/*  File produced by Kranc */

#define KRANC_C

#include <algorithm>
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameters.h"
#include "Kranc.hh"
#include "Differencing.h"
#include "loopcontrol.h"
#include "OpenCLRunTime.h"
#include "vectors.h"

namespace ML_BSSN_CL {

extern "C" void ML_BSSN_CL_InitialADMBase2Interior_SelectBCs(CCTK_ARGUMENTS)
{
  #ifdef DECLARE_CCTK_ARGUMENTS_ML_BSSN_CL_InitialADMBase2Interior_SelectBCs
  DECLARE_CCTK_ARGUMENTS_CHECKED(ML_BSSN_CL_InitialADMBase2Interior_SelectBCs);
  #else
  DECLARE_CCTK_ARGUMENTS;
  #endif
  DECLARE_CCTK_PARAMETERS;
  
  if (cctk_iteration % ML_BSSN_CL_InitialADMBase2Interior_calc_every != ML_BSSN_CL_InitialADMBase2Interior_calc_offset)
    return;
  CCTK_INT ierr CCTK_ATTRIBUTE_UNUSED = 0;
  ierr = KrancBdy_SelectGroupForBC(cctkGH, CCTK_ALL_FACES, GetBoundaryWidth(cctkGH), -1 /* no table */, "ML_BSSN_CL::ML_dtlapse","flat");
  if (ierr < 0)
    CCTK_WARN(CCTK_WARN_ALERT, "Failed to register flat BC for ML_BSSN_CL::ML_dtlapse.");
  ierr = KrancBdy_SelectGroupForBC(cctkGH, CCTK_ALL_FACES, GetBoundaryWidth(cctkGH), -1 /* no table */, "ML_BSSN_CL::ML_dtshift","flat");
  if (ierr < 0)
    CCTK_WARN(CCTK_WARN_ALERT, "Failed to register flat BC for ML_BSSN_CL::ML_dtshift.");
  ierr = KrancBdy_SelectGroupForBC(cctkGH, CCTK_ALL_FACES, GetBoundaryWidth(cctkGH), -1 /* no table */, "ML_BSSN_CL::ML_Gamma","flat");
  if (ierr < 0)
    CCTK_WARN(CCTK_WARN_ALERT, "Failed to register flat BC for ML_BSSN_CL::ML_Gamma.");
  return;
}

static void ML_BSSN_CL_InitialADMBase2Interior_Body(const cGH* restrict const cctkGH, const int dir, const int face, const CCTK_REAL normal[3], const CCTK_REAL tangentA[3], const CCTK_REAL tangentB[3], const int imin[3], const int imax[3], const int n_subblock_gfs, CCTK_REAL* restrict const subblock_gfs[])
{
  DECLARE_CCTK_ARGUMENTS;
  DECLARE_CCTK_PARAMETERS;
  
  const char* const source =
  "/* Include user-supplied include files */\n"
  "/* Initialise finite differencing variables */\n"
  "const ptrdiff_t di CCTK_ATTRIBUTE_UNUSED = 1;\n"
  "const ptrdiff_t dj CCTK_ATTRIBUTE_UNUSED = \n"
  "  CCTK_GFINDEX3D(cctkGH,0,1,0) - CCTK_GFINDEX3D(cctkGH,0,0,0);\n"
  "const ptrdiff_t dk CCTK_ATTRIBUTE_UNUSED = \n"
  "  CCTK_GFINDEX3D(cctkGH,0,0,1) - CCTK_GFINDEX3D(cctkGH,0,0,0);\n"
  "const ptrdiff_t cdi CCTK_ATTRIBUTE_UNUSED = sizeof(CCTK_REAL) * di;\n"
  "const ptrdiff_t cdj CCTK_ATTRIBUTE_UNUSED = sizeof(CCTK_REAL) * dj;\n"
  "const ptrdiff_t cdk CCTK_ATTRIBUTE_UNUSED = sizeof(CCTK_REAL) * dk;\n"
  "const ptrdiff_t cctkLbnd1 CCTK_ATTRIBUTE_UNUSED = cctk_lbnd[0];\n"
  "const ptrdiff_t cctkLbnd2 CCTK_ATTRIBUTE_UNUSED = cctk_lbnd[1];\n"
  "const ptrdiff_t cctkLbnd3 CCTK_ATTRIBUTE_UNUSED = cctk_lbnd[2];\n"
  "const CCTK_REAL_VEC t CCTK_ATTRIBUTE_UNUSED = ToReal(cctk_time);\n"
  "const CCTK_REAL_VEC cctkOriginSpace1 CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_ORIGIN_SPACE(0));\n"
  "const CCTK_REAL_VEC cctkOriginSpace2 CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_ORIGIN_SPACE(1));\n"
  "const CCTK_REAL_VEC cctkOriginSpace3 CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_ORIGIN_SPACE(2));\n"
  "const CCTK_REAL_VEC dt CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_DELTA_TIME);\n"
  "const CCTK_REAL_VEC dx CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_DELTA_SPACE(0));\n"
  "const CCTK_REAL_VEC dy CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_DELTA_SPACE(1));\n"
  "const CCTK_REAL_VEC dz CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(CCTK_DELTA_SPACE(2));\n"
  "const CCTK_REAL_VEC dxi CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),dx);\n"
  "const CCTK_REAL_VEC dyi CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),dy);\n"
  "const CCTK_REAL_VEC dzi CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),dz);\n"
  "const CCTK_REAL_VEC khalf CCTK_ATTRIBUTE_UNUSED = ToReal(0.5);\n"
  "const CCTK_REAL_VEC kthird CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(0.333333333333333333333333333333);\n"
  "const CCTK_REAL_VEC ktwothird CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(0.666666666666666666666666666667);\n"
  "const CCTK_REAL_VEC kfourthird CCTK_ATTRIBUTE_UNUSED = \n"
  "  ToReal(1.33333333333333333333333333333);\n"
  "const CCTK_REAL_VEC hdxi CCTK_ATTRIBUTE_UNUSED = \n"
  "  kmul(dxi,ToReal(0.5));\n"
  "const CCTK_REAL_VEC hdyi CCTK_ATTRIBUTE_UNUSED = \n"
  "  kmul(dyi,ToReal(0.5));\n"
  "const CCTK_REAL_VEC hdzi CCTK_ATTRIBUTE_UNUSED = \n"
  "  kmul(dzi,ToReal(0.5));\n"
  "/* Initialize predefined quantities */\n"
  "const CCTK_REAL_VEC p1o1024dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0009765625),dx);\n"
  "const CCTK_REAL_VEC p1o1024dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0009765625),dy);\n"
  "const CCTK_REAL_VEC p1o1024dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0009765625),dz);\n"
  "const CCTK_REAL_VEC p1o120dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00833333333333333333333333333333),dx);\n"
  "const CCTK_REAL_VEC p1o120dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00833333333333333333333333333333),dy);\n"
  "const CCTK_REAL_VEC p1o120dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00833333333333333333333333333333),dz);\n"
  "const CCTK_REAL_VEC p1o12dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0833333333333333333333333333333),dx);\n"
  "const CCTK_REAL_VEC p1o12dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0833333333333333333333333333333),dy);\n"
  "const CCTK_REAL_VEC p1o12dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0833333333333333333333333333333),dz);\n"
  "const CCTK_REAL_VEC p1o144dxdy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00694444444444444444444444444444),kmul(dx,dy));\n"
  "const CCTK_REAL_VEC p1o144dxdz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00694444444444444444444444444444),kmul(dx,dz));\n"
  "const CCTK_REAL_VEC p1o144dydz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00694444444444444444444444444444),kmul(dy,dz));\n"
  "const CCTK_REAL_VEC p1o1680dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000595238095238095238095238095238),dx);\n"
  "const CCTK_REAL_VEC p1o1680dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000595238095238095238095238095238),dy);\n"
  "const CCTK_REAL_VEC p1o1680dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000595238095238095238095238095238),dz);\n"
  "const CCTK_REAL_VEC p1o180dx2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00555555555555555555555555555556),kmul(dx,dx));\n"
  "const CCTK_REAL_VEC p1o180dy2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00555555555555555555555555555556),kmul(dy,dy));\n"
  "const CCTK_REAL_VEC p1o180dz2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00555555555555555555555555555556),kmul(dz,dz));\n"
  "const CCTK_REAL_VEC p1o24dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0416666666666666666666666666667),dx);\n"
  "const CCTK_REAL_VEC p1o24dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0416666666666666666666666666667),dy);\n"
  "const CCTK_REAL_VEC p1o24dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0416666666666666666666666666667),dz);\n"
  "const CCTK_REAL_VEC p1o2dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.5),dx);\n"
  "const CCTK_REAL_VEC p1o2dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.5),dy);\n"
  "const CCTK_REAL_VEC p1o2dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.5),dz);\n"
  "const CCTK_REAL_VEC p1o3600dxdy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000277777777777777777777777777778),kmul(dx,dy));\n"
  "const CCTK_REAL_VEC p1o3600dxdz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000277777777777777777777777777778),kmul(dx,dz));\n"
  "const CCTK_REAL_VEC p1o3600dydz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000277777777777777777777777777778),kmul(dy,dz));\n"
  "const CCTK_REAL_VEC p1o4dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),dx);\n"
  "const CCTK_REAL_VEC p1o4dxdy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),kmul(dx,dy));\n"
  "const CCTK_REAL_VEC p1o4dxdz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),kmul(dx,dz));\n"
  "const CCTK_REAL_VEC p1o4dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),dy);\n"
  "const CCTK_REAL_VEC p1o4dydz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),kmul(dy,dz));\n"
  "const CCTK_REAL_VEC p1o4dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.25),dz);\n"
  "const CCTK_REAL_VEC p1o5040dx2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000198412698412698412698412698413),kmul(dx,dx));\n"
  "const CCTK_REAL_VEC p1o5040dy2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000198412698412698412698412698413),kmul(dy,dy));\n"
  "const CCTK_REAL_VEC p1o5040dz2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.000198412698412698412698412698413),kmul(dz,dz));\n"
  "const CCTK_REAL_VEC p1o560dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00178571428571428571428571428571),dx);\n"
  "const CCTK_REAL_VEC p1o560dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00178571428571428571428571428571),dy);\n"
  "const CCTK_REAL_VEC p1o560dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00178571428571428571428571428571),dz);\n"
  "const CCTK_REAL_VEC p1o60dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0166666666666666666666666666667),dx);\n"
  "const CCTK_REAL_VEC p1o60dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0166666666666666666666666666667),dy);\n"
  "const CCTK_REAL_VEC p1o60dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.0166666666666666666666666666667),dz);\n"
  "const CCTK_REAL_VEC p1o64dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.015625),dx);\n"
  "const CCTK_REAL_VEC p1o64dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.015625),dy);\n"
  "const CCTK_REAL_VEC p1o64dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.015625),dz);\n"
  "const CCTK_REAL_VEC p1o6dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.166666666666666666666666666667),dx);\n"
  "const CCTK_REAL_VEC p1o6dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.166666666666666666666666666667),dy);\n"
  "const CCTK_REAL_VEC p1o6dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.166666666666666666666666666667),dz);\n"
  "const CCTK_REAL_VEC p1o705600dxdy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1.41723356009070294784580498866e-6),kmul(dx,dy));\n"
  "const CCTK_REAL_VEC p1o705600dxdz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1.41723356009070294784580498866e-6),kmul(dx,dz));\n"
  "const CCTK_REAL_VEC p1o705600dydz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1.41723356009070294784580498866e-6),kmul(dy,dz));\n"
  "const CCTK_REAL_VEC p1o840dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00119047619047619047619047619048),dx);\n"
  "const CCTK_REAL_VEC p1o840dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00119047619047619047619047619048),dy);\n"
  "const CCTK_REAL_VEC p1o840dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(0.00119047619047619047619047619048),dz);\n"
  "const CCTK_REAL_VEC p1odx2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),kmul(dx,dx));\n"
  "const CCTK_REAL_VEC p1ody2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),kmul(dy,dy));\n"
  "const CCTK_REAL_VEC p1odz2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(1),kmul(dz,dz));\n"
  "const CCTK_REAL_VEC pm1o120dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00833333333333333333333333333333),dx);\n"
  "const CCTK_REAL_VEC pm1o120dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00833333333333333333333333333333),dy);\n"
  "const CCTK_REAL_VEC pm1o120dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00833333333333333333333333333333),dz);\n"
  "const CCTK_REAL_VEC pm1o12dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),dx);\n"
  "const CCTK_REAL_VEC pm1o12dx2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),kmul(dx,dx));\n"
  "const CCTK_REAL_VEC pm1o12dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),dy);\n"
  "const CCTK_REAL_VEC pm1o12dy2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),kmul(dy,dy));\n"
  "const CCTK_REAL_VEC pm1o12dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),dz);\n"
  "const CCTK_REAL_VEC pm1o12dz2 CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0833333333333333333333333333333),kmul(dz,dz));\n"
  "const CCTK_REAL_VEC pm1o16dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0625),dx);\n"
  "const CCTK_REAL_VEC pm1o16dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0625),dy);\n"
  "const CCTK_REAL_VEC pm1o16dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0625),dz);\n"
  "const CCTK_REAL_VEC pm1o256dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00390625),dx);\n"
  "const CCTK_REAL_VEC pm1o256dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00390625),dy);\n"
  "const CCTK_REAL_VEC pm1o256dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.00390625),dz);\n"
  "const CCTK_REAL_VEC pm1o2dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.5),dx);\n"
  "const CCTK_REAL_VEC pm1o2dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.5),dy);\n"
  "const CCTK_REAL_VEC pm1o2dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.5),dz);\n"
  "const CCTK_REAL_VEC pm1o4dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.25),dx);\n"
  "const CCTK_REAL_VEC pm1o4dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.25),dy);\n"
  "const CCTK_REAL_VEC pm1o4dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.25),dz);\n"
  "const CCTK_REAL_VEC pm1o60dx CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0166666666666666666666666666667),dx);\n"
  "const CCTK_REAL_VEC pm1o60dy CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0166666666666666666666666666667),dy);\n"
  "const CCTK_REAL_VEC pm1o60dz CCTK_ATTRIBUTE_UNUSED = kdiv(ToReal(-0.0166666666666666666666666666667),dz);\n"
  "/* Jacobian variable pointers */\n"
  "const bool usejacobian1 = (!CCTK_IsFunctionAliased(\"MultiPatch_GetMap\") || MultiPatch_GetMap(cctkGH) != jacobian_identity_map)\n"
  "                      && strlen(jacobian_group) > 0;\n"
  "const bool usejacobian = assume_use_jacobian>=0 ? assume_use_jacobian : usejacobian1;\n"
  "if (usejacobian && (strlen(jacobian_derivative_group) == 0))\n"
  "{\n"
  "  CCTK_WARN(CCTK_WARN_ALERT, \"GenericFD::jacobian_group and GenericFD::jacobian_derivative_group must both be set to valid group names\");\n"
  "}\n"
  "\n"
  "const CCTK_REAL* restrict jacobian_ptrs[9];\n"
  "if (usejacobian) GroupDataPointers(cctkGH, jacobian_group,\n"
  "                                              9, jacobian_ptrs);\n"
  "\n"
  "const CCTK_REAL* restrict const J11 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[0] : 0;\n"
  "const CCTK_REAL* restrict const J12 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[1] : 0;\n"
  "const CCTK_REAL* restrict const J13 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[2] : 0;\n"
  "const CCTK_REAL* restrict const J21 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[3] : 0;\n"
  "const CCTK_REAL* restrict const J22 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[4] : 0;\n"
  "const CCTK_REAL* restrict const J23 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[5] : 0;\n"
  "const CCTK_REAL* restrict const J31 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[6] : 0;\n"
  "const CCTK_REAL* restrict const J32 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[7] : 0;\n"
  "const CCTK_REAL* restrict const J33 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_ptrs[8] : 0;\n"
  "\n"
  "const CCTK_REAL* restrict jacobian_determinant_ptrs[1] CCTK_ATTRIBUTE_UNUSED;\n"
  "if (usejacobian && strlen(jacobian_determinant_group) > 0) GroupDataPointers(cctkGH, jacobian_determinant_group,\n"
  "                                              1, jacobian_determinant_ptrs);\n"
  "\n"
  "const CCTK_REAL* restrict const detJ CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_determinant_ptrs[0] : 0;\n"
  "\n"
  "const CCTK_REAL* restrict jacobian_inverse_ptrs[9] CCTK_ATTRIBUTE_UNUSED;\n"
  "if (usejacobian && strlen(jacobian_inverse_group) > 0) GroupDataPointers(cctkGH, jacobian_inverse_group,\n"
  "                                              9, jacobian_inverse_ptrs);\n"
  "\n"
  "const CCTK_REAL* restrict const iJ11 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[0] : 0;\n"
  "const CCTK_REAL* restrict const iJ12 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[1] : 0;\n"
  "const CCTK_REAL* restrict const iJ13 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[2] : 0;\n"
  "const CCTK_REAL* restrict const iJ21 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[3] : 0;\n"
  "const CCTK_REAL* restrict const iJ22 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[4] : 0;\n"
  "const CCTK_REAL* restrict const iJ23 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[5] : 0;\n"
  "const CCTK_REAL* restrict const iJ31 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[6] : 0;\n"
  "const CCTK_REAL* restrict const iJ32 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[7] : 0;\n"
  "const CCTK_REAL* restrict const iJ33 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_inverse_ptrs[8] : 0;\n"
  "\n"
  "const CCTK_REAL* restrict jacobian_derivative_ptrs[18] CCTK_ATTRIBUTE_UNUSED;\n"
  "if (usejacobian) GroupDataPointers(cctkGH, jacobian_derivative_group,\n"
  "                                    18, jacobian_derivative_ptrs);\n"
  "\n"
  "const CCTK_REAL* restrict const dJ111 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[0] : 0;\n"
  "const CCTK_REAL* restrict const dJ112 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[1] : 0;\n"
  "const CCTK_REAL* restrict const dJ113 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[2] : 0;\n"
  "const CCTK_REAL* restrict const dJ122 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[3] : 0;\n"
  "const CCTK_REAL* restrict const dJ123 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[4] : 0;\n"
  "const CCTK_REAL* restrict const dJ133 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[5] : 0;\n"
  "const CCTK_REAL* restrict const dJ211 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[6] : 0;\n"
  "const CCTK_REAL* restrict const dJ212 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[7] : 0;\n"
  "const CCTK_REAL* restrict const dJ213 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[8] : 0;\n"
  "const CCTK_REAL* restrict const dJ222 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[9] : 0;\n"
  "const CCTK_REAL* restrict const dJ223 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[10] : 0;\n"
  "const CCTK_REAL* restrict const dJ233 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[11] : 0;\n"
  "const CCTK_REAL* restrict const dJ311 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[12] : 0;\n"
  "const CCTK_REAL* restrict const dJ312 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[13] : 0;\n"
  "const CCTK_REAL* restrict const dJ313 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[14] : 0;\n"
  "const CCTK_REAL* restrict const dJ322 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[15] : 0;\n"
  "const CCTK_REAL* restrict const dJ323 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[16] : 0;\n"
  "const CCTK_REAL* restrict const dJ333 CCTK_ATTRIBUTE_UNUSED = usejacobian ? jacobian_derivative_ptrs[17] : 0;\n"
  "/* Assign local copies of arrays functions */\n"
  "\n"
  "\n"
  "/* Calculate temporaries and arrays functions */\n"
  "/* Copy local copies back to grid functions */\n"
  "/* Loop over the grid points */\n"
  "const int imin0=imin[0];\n"
  "const int imin1=imin[1];\n"
  "const int imin2=imin[2];\n"
  "const int imax0=imax[0];\n"
  "const int imax1=imax[1];\n"
  "const int imax2=imax[2];\n"
  "#pragma omp parallel\n"
  "CCTK_LOOP3STR(ML_BSSN_CL_InitialADMBase2Interior,\n"
  "  i,j,k, imin0,imin1,imin2, imax0,imax1,imax2,\n"
  "  cctk_ash[0],cctk_ash[1],cctk_ash[2],\n"
  "  vecimin,vecimax, CCTK_REAL_VEC_SIZE)\n"
  "{\n"
  "  const ptrdiff_t index CCTK_ATTRIBUTE_UNUSED = di*i + dj*j + dk*k;\n"
  "  /* Assign local copies of grid functions */\n"
  "  \n"
  "  CCTK_REAL_VEC alpL CCTK_ATTRIBUTE_UNUSED = vec_load(alp[index]);\n"
  "  CCTK_REAL_VEC betaxL CCTK_ATTRIBUTE_UNUSED = vec_load(betax[index]);\n"
  "  CCTK_REAL_VEC betayL CCTK_ATTRIBUTE_UNUSED = vec_load(betay[index]);\n"
  "  CCTK_REAL_VEC betazL CCTK_ATTRIBUTE_UNUSED = vec_load(betaz[index]);\n"
  "  CCTK_REAL_VEC dtalpL CCTK_ATTRIBUTE_UNUSED = vec_load(dtalp[index]);\n"
  "  CCTK_REAL_VEC dtbetaxL CCTK_ATTRIBUTE_UNUSED = \n"
  "    vec_load(dtbetax[index]);\n"
  "  CCTK_REAL_VEC dtbetayL CCTK_ATTRIBUTE_UNUSED = \n"
  "    vec_load(dtbetay[index]);\n"
  "  CCTK_REAL_VEC dtbetazL CCTK_ATTRIBUTE_UNUSED = \n"
  "    vec_load(dtbetaz[index]);\n"
  "  CCTK_REAL_VEC gt11L CCTK_ATTRIBUTE_UNUSED = vec_load(gt11[index]);\n"
  "  CCTK_REAL_VEC gt12L CCTK_ATTRIBUTE_UNUSED = vec_load(gt12[index]);\n"
  "  CCTK_REAL_VEC gt13L CCTK_ATTRIBUTE_UNUSED = vec_load(gt13[index]);\n"
  "  CCTK_REAL_VEC gt22L CCTK_ATTRIBUTE_UNUSED = vec_load(gt22[index]);\n"
  "  CCTK_REAL_VEC gt23L CCTK_ATTRIBUTE_UNUSED = vec_load(gt23[index]);\n"
  "  CCTK_REAL_VEC gt33L CCTK_ATTRIBUTE_UNUSED = vec_load(gt33[index]);\n"
  "  CCTK_REAL_VEC gxxL CCTK_ATTRIBUTE_UNUSED = vec_load(gxx[index]);\n"
  "  CCTK_REAL_VEC gxyL CCTK_ATTRIBUTE_UNUSED = vec_load(gxy[index]);\n"
  "  CCTK_REAL_VEC gxzL CCTK_ATTRIBUTE_UNUSED = vec_load(gxz[index]);\n"
  "  CCTK_REAL_VEC gyyL CCTK_ATTRIBUTE_UNUSED = vec_load(gyy[index]);\n"
  "  CCTK_REAL_VEC gyzL CCTK_ATTRIBUTE_UNUSED = vec_load(gyz[index]);\n"
  "  CCTK_REAL_VEC gzzL CCTK_ATTRIBUTE_UNUSED = vec_load(gzz[index]);\n"
  "  CCTK_REAL_VEC phiL CCTK_ATTRIBUTE_UNUSED = vec_load(phi[index]);\n"
  "  CCTK_REAL_VEC rL CCTK_ATTRIBUTE_UNUSED = vec_load(r[index]);\n"
  "  \n"
  "  \n"
  "  CCTK_REAL_VEC J11L, J12L, J13L, J21L, J22L, J23L, J31L, J32L, J33L CCTK_ATTRIBUTE_UNUSED ;\n"
  "  \n"
  "  if (usejacobian)\n"
  "  {\n"
  "    J11L = vec_load(J11[index]);\n"
  "    J12L = vec_load(J12[index]);\n"
  "    J13L = vec_load(J13[index]);\n"
  "    J21L = vec_load(J21[index]);\n"
  "    J22L = vec_load(J22[index]);\n"
  "    J23L = vec_load(J23[index]);\n"
  "    J31L = vec_load(J31[index]);\n"
  "    J32L = vec_load(J32[index]);\n"
  "    J33L = vec_load(J33[index]);\n"
  "  }\n"
  "  /* Include user supplied include files */\n"
  "  /* Precompute derivatives */\n"
  "  CCTK_REAL_VEC PDupwindNthSymm1alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm2alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm3alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti1alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti2alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti3alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm1betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm2betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm3betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti1betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti2betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti3betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm1betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm2betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm3betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti1betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti2betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti3betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm1betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm2betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthSymm3betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti1betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti2betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDupwindNthAnti3betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth1gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth2gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC PDstandardNth3gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  \n"
  "  switch (fdOrder)\n"
  "  {\n"
  "    case 2:\n"
  "    {\n"
  "      PDupwindNthSymm1alp = PDupwindNthSymmfdOrder21(&alp[index]);\n"
  "      PDupwindNthSymm2alp = PDupwindNthSymmfdOrder22(&alp[index]);\n"
  "      PDupwindNthSymm3alp = PDupwindNthSymmfdOrder23(&alp[index]);\n"
  "      PDupwindNthAnti1alp = PDupwindNthAntifdOrder21(&alp[index]);\n"
  "      PDupwindNthAnti2alp = PDupwindNthAntifdOrder22(&alp[index]);\n"
  "      PDupwindNthAnti3alp = PDupwindNthAntifdOrder23(&alp[index]);\n"
  "      PDupwindNthSymm1betax = PDupwindNthSymmfdOrder21(&betax[index]);\n"
  "      PDupwindNthSymm2betax = PDupwindNthSymmfdOrder22(&betax[index]);\n"
  "      PDupwindNthSymm3betax = PDupwindNthSymmfdOrder23(&betax[index]);\n"
  "      PDupwindNthAnti1betax = PDupwindNthAntifdOrder21(&betax[index]);\n"
  "      PDupwindNthAnti2betax = PDupwindNthAntifdOrder22(&betax[index]);\n"
  "      PDupwindNthAnti3betax = PDupwindNthAntifdOrder23(&betax[index]);\n"
  "      PDupwindNthSymm1betay = PDupwindNthSymmfdOrder21(&betay[index]);\n"
  "      PDupwindNthSymm2betay = PDupwindNthSymmfdOrder22(&betay[index]);\n"
  "      PDupwindNthSymm3betay = PDupwindNthSymmfdOrder23(&betay[index]);\n"
  "      PDupwindNthAnti1betay = PDupwindNthAntifdOrder21(&betay[index]);\n"
  "      PDupwindNthAnti2betay = PDupwindNthAntifdOrder22(&betay[index]);\n"
  "      PDupwindNthAnti3betay = PDupwindNthAntifdOrder23(&betay[index]);\n"
  "      PDupwindNthSymm1betaz = PDupwindNthSymmfdOrder21(&betaz[index]);\n"
  "      PDupwindNthSymm2betaz = PDupwindNthSymmfdOrder22(&betaz[index]);\n"
  "      PDupwindNthSymm3betaz = PDupwindNthSymmfdOrder23(&betaz[index]);\n"
  "      PDupwindNthAnti1betaz = PDupwindNthAntifdOrder21(&betaz[index]);\n"
  "      PDupwindNthAnti2betaz = PDupwindNthAntifdOrder22(&betaz[index]);\n"
  "      PDupwindNthAnti3betaz = PDupwindNthAntifdOrder23(&betaz[index]);\n"
  "      PDstandardNth1gt11 = PDstandardNthfdOrder21(&gt11[index]);\n"
  "      PDstandardNth2gt11 = PDstandardNthfdOrder22(&gt11[index]);\n"
  "      PDstandardNth3gt11 = PDstandardNthfdOrder23(&gt11[index]);\n"
  "      PDstandardNth1gt12 = PDstandardNthfdOrder21(&gt12[index]);\n"
  "      PDstandardNth2gt12 = PDstandardNthfdOrder22(&gt12[index]);\n"
  "      PDstandardNth3gt12 = PDstandardNthfdOrder23(&gt12[index]);\n"
  "      PDstandardNth1gt13 = PDstandardNthfdOrder21(&gt13[index]);\n"
  "      PDstandardNth2gt13 = PDstandardNthfdOrder22(&gt13[index]);\n"
  "      PDstandardNth3gt13 = PDstandardNthfdOrder23(&gt13[index]);\n"
  "      PDstandardNth1gt22 = PDstandardNthfdOrder21(&gt22[index]);\n"
  "      PDstandardNth2gt22 = PDstandardNthfdOrder22(&gt22[index]);\n"
  "      PDstandardNth3gt22 = PDstandardNthfdOrder23(&gt22[index]);\n"
  "      PDstandardNth1gt23 = PDstandardNthfdOrder21(&gt23[index]);\n"
  "      PDstandardNth2gt23 = PDstandardNthfdOrder22(&gt23[index]);\n"
  "      PDstandardNth3gt23 = PDstandardNthfdOrder23(&gt23[index]);\n"
  "      PDstandardNth1gt33 = PDstandardNthfdOrder21(&gt33[index]);\n"
  "      PDstandardNth2gt33 = PDstandardNthfdOrder22(&gt33[index]);\n"
  "      PDstandardNth3gt33 = PDstandardNthfdOrder23(&gt33[index]);\n"
  "      break;\n"
  "    }\n"
  "    \n"
  "    case 4:\n"
  "    {\n"
  "      PDupwindNthSymm1alp = PDupwindNthSymmfdOrder41(&alp[index]);\n"
  "      PDupwindNthSymm2alp = PDupwindNthSymmfdOrder42(&alp[index]);\n"
  "      PDupwindNthSymm3alp = PDupwindNthSymmfdOrder43(&alp[index]);\n"
  "      PDupwindNthAnti1alp = PDupwindNthAntifdOrder41(&alp[index]);\n"
  "      PDupwindNthAnti2alp = PDupwindNthAntifdOrder42(&alp[index]);\n"
  "      PDupwindNthAnti3alp = PDupwindNthAntifdOrder43(&alp[index]);\n"
  "      PDupwindNthSymm1betax = PDupwindNthSymmfdOrder41(&betax[index]);\n"
  "      PDupwindNthSymm2betax = PDupwindNthSymmfdOrder42(&betax[index]);\n"
  "      PDupwindNthSymm3betax = PDupwindNthSymmfdOrder43(&betax[index]);\n"
  "      PDupwindNthAnti1betax = PDupwindNthAntifdOrder41(&betax[index]);\n"
  "      PDupwindNthAnti2betax = PDupwindNthAntifdOrder42(&betax[index]);\n"
  "      PDupwindNthAnti3betax = PDupwindNthAntifdOrder43(&betax[index]);\n"
  "      PDupwindNthSymm1betay = PDupwindNthSymmfdOrder41(&betay[index]);\n"
  "      PDupwindNthSymm2betay = PDupwindNthSymmfdOrder42(&betay[index]);\n"
  "      PDupwindNthSymm3betay = PDupwindNthSymmfdOrder43(&betay[index]);\n"
  "      PDupwindNthAnti1betay = PDupwindNthAntifdOrder41(&betay[index]);\n"
  "      PDupwindNthAnti2betay = PDupwindNthAntifdOrder42(&betay[index]);\n"
  "      PDupwindNthAnti3betay = PDupwindNthAntifdOrder43(&betay[index]);\n"
  "      PDupwindNthSymm1betaz = PDupwindNthSymmfdOrder41(&betaz[index]);\n"
  "      PDupwindNthSymm2betaz = PDupwindNthSymmfdOrder42(&betaz[index]);\n"
  "      PDupwindNthSymm3betaz = PDupwindNthSymmfdOrder43(&betaz[index]);\n"
  "      PDupwindNthAnti1betaz = PDupwindNthAntifdOrder41(&betaz[index]);\n"
  "      PDupwindNthAnti2betaz = PDupwindNthAntifdOrder42(&betaz[index]);\n"
  "      PDupwindNthAnti3betaz = PDupwindNthAntifdOrder43(&betaz[index]);\n"
  "      PDstandardNth1gt11 = PDstandardNthfdOrder41(&gt11[index]);\n"
  "      PDstandardNth2gt11 = PDstandardNthfdOrder42(&gt11[index]);\n"
  "      PDstandardNth3gt11 = PDstandardNthfdOrder43(&gt11[index]);\n"
  "      PDstandardNth1gt12 = PDstandardNthfdOrder41(&gt12[index]);\n"
  "      PDstandardNth2gt12 = PDstandardNthfdOrder42(&gt12[index]);\n"
  "      PDstandardNth3gt12 = PDstandardNthfdOrder43(&gt12[index]);\n"
  "      PDstandardNth1gt13 = PDstandardNthfdOrder41(&gt13[index]);\n"
  "      PDstandardNth2gt13 = PDstandardNthfdOrder42(&gt13[index]);\n"
  "      PDstandardNth3gt13 = PDstandardNthfdOrder43(&gt13[index]);\n"
  "      PDstandardNth1gt22 = PDstandardNthfdOrder41(&gt22[index]);\n"
  "      PDstandardNth2gt22 = PDstandardNthfdOrder42(&gt22[index]);\n"
  "      PDstandardNth3gt22 = PDstandardNthfdOrder43(&gt22[index]);\n"
  "      PDstandardNth1gt23 = PDstandardNthfdOrder41(&gt23[index]);\n"
  "      PDstandardNth2gt23 = PDstandardNthfdOrder42(&gt23[index]);\n"
  "      PDstandardNth3gt23 = PDstandardNthfdOrder43(&gt23[index]);\n"
  "      PDstandardNth1gt33 = PDstandardNthfdOrder41(&gt33[index]);\n"
  "      PDstandardNth2gt33 = PDstandardNthfdOrder42(&gt33[index]);\n"
  "      PDstandardNth3gt33 = PDstandardNthfdOrder43(&gt33[index]);\n"
  "      break;\n"
  "    }\n"
  "    \n"
  "    case 6:\n"
  "    {\n"
  "      PDupwindNthSymm1alp = PDupwindNthSymmfdOrder61(&alp[index]);\n"
  "      PDupwindNthSymm2alp = PDupwindNthSymmfdOrder62(&alp[index]);\n"
  "      PDupwindNthSymm3alp = PDupwindNthSymmfdOrder63(&alp[index]);\n"
  "      PDupwindNthAnti1alp = PDupwindNthAntifdOrder61(&alp[index]);\n"
  "      PDupwindNthAnti2alp = PDupwindNthAntifdOrder62(&alp[index]);\n"
  "      PDupwindNthAnti3alp = PDupwindNthAntifdOrder63(&alp[index]);\n"
  "      PDupwindNthSymm1betax = PDupwindNthSymmfdOrder61(&betax[index]);\n"
  "      PDupwindNthSymm2betax = PDupwindNthSymmfdOrder62(&betax[index]);\n"
  "      PDupwindNthSymm3betax = PDupwindNthSymmfdOrder63(&betax[index]);\n"
  "      PDupwindNthAnti1betax = PDupwindNthAntifdOrder61(&betax[index]);\n"
  "      PDupwindNthAnti2betax = PDupwindNthAntifdOrder62(&betax[index]);\n"
  "      PDupwindNthAnti3betax = PDupwindNthAntifdOrder63(&betax[index]);\n"
  "      PDupwindNthSymm1betay = PDupwindNthSymmfdOrder61(&betay[index]);\n"
  "      PDupwindNthSymm2betay = PDupwindNthSymmfdOrder62(&betay[index]);\n"
  "      PDupwindNthSymm3betay = PDupwindNthSymmfdOrder63(&betay[index]);\n"
  "      PDupwindNthAnti1betay = PDupwindNthAntifdOrder61(&betay[index]);\n"
  "      PDupwindNthAnti2betay = PDupwindNthAntifdOrder62(&betay[index]);\n"
  "      PDupwindNthAnti3betay = PDupwindNthAntifdOrder63(&betay[index]);\n"
  "      PDupwindNthSymm1betaz = PDupwindNthSymmfdOrder61(&betaz[index]);\n"
  "      PDupwindNthSymm2betaz = PDupwindNthSymmfdOrder62(&betaz[index]);\n"
  "      PDupwindNthSymm3betaz = PDupwindNthSymmfdOrder63(&betaz[index]);\n"
  "      PDupwindNthAnti1betaz = PDupwindNthAntifdOrder61(&betaz[index]);\n"
  "      PDupwindNthAnti2betaz = PDupwindNthAntifdOrder62(&betaz[index]);\n"
  "      PDupwindNthAnti3betaz = PDupwindNthAntifdOrder63(&betaz[index]);\n"
  "      PDstandardNth1gt11 = PDstandardNthfdOrder61(&gt11[index]);\n"
  "      PDstandardNth2gt11 = PDstandardNthfdOrder62(&gt11[index]);\n"
  "      PDstandardNth3gt11 = PDstandardNthfdOrder63(&gt11[index]);\n"
  "      PDstandardNth1gt12 = PDstandardNthfdOrder61(&gt12[index]);\n"
  "      PDstandardNth2gt12 = PDstandardNthfdOrder62(&gt12[index]);\n"
  "      PDstandardNth3gt12 = PDstandardNthfdOrder63(&gt12[index]);\n"
  "      PDstandardNth1gt13 = PDstandardNthfdOrder61(&gt13[index]);\n"
  "      PDstandardNth2gt13 = PDstandardNthfdOrder62(&gt13[index]);\n"
  "      PDstandardNth3gt13 = PDstandardNthfdOrder63(&gt13[index]);\n"
  "      PDstandardNth1gt22 = PDstandardNthfdOrder61(&gt22[index]);\n"
  "      PDstandardNth2gt22 = PDstandardNthfdOrder62(&gt22[index]);\n"
  "      PDstandardNth3gt22 = PDstandardNthfdOrder63(&gt22[index]);\n"
  "      PDstandardNth1gt23 = PDstandardNthfdOrder61(&gt23[index]);\n"
  "      PDstandardNth2gt23 = PDstandardNthfdOrder62(&gt23[index]);\n"
  "      PDstandardNth3gt23 = PDstandardNthfdOrder63(&gt23[index]);\n"
  "      PDstandardNth1gt33 = PDstandardNthfdOrder61(&gt33[index]);\n"
  "      PDstandardNth2gt33 = PDstandardNthfdOrder62(&gt33[index]);\n"
  "      PDstandardNth3gt33 = PDstandardNthfdOrder63(&gt33[index]);\n"
  "      break;\n"
  "    }\n"
  "    \n"
  "    case 8:\n"
  "    {\n"
  "      PDupwindNthSymm1alp = PDupwindNthSymmfdOrder81(&alp[index]);\n"
  "      PDupwindNthSymm2alp = PDupwindNthSymmfdOrder82(&alp[index]);\n"
  "      PDupwindNthSymm3alp = PDupwindNthSymmfdOrder83(&alp[index]);\n"
  "      PDupwindNthAnti1alp = PDupwindNthAntifdOrder81(&alp[index]);\n"
  "      PDupwindNthAnti2alp = PDupwindNthAntifdOrder82(&alp[index]);\n"
  "      PDupwindNthAnti3alp = PDupwindNthAntifdOrder83(&alp[index]);\n"
  "      PDupwindNthSymm1betax = PDupwindNthSymmfdOrder81(&betax[index]);\n"
  "      PDupwindNthSymm2betax = PDupwindNthSymmfdOrder82(&betax[index]);\n"
  "      PDupwindNthSymm3betax = PDupwindNthSymmfdOrder83(&betax[index]);\n"
  "      PDupwindNthAnti1betax = PDupwindNthAntifdOrder81(&betax[index]);\n"
  "      PDupwindNthAnti2betax = PDupwindNthAntifdOrder82(&betax[index]);\n"
  "      PDupwindNthAnti3betax = PDupwindNthAntifdOrder83(&betax[index]);\n"
  "      PDupwindNthSymm1betay = PDupwindNthSymmfdOrder81(&betay[index]);\n"
  "      PDupwindNthSymm2betay = PDupwindNthSymmfdOrder82(&betay[index]);\n"
  "      PDupwindNthSymm3betay = PDupwindNthSymmfdOrder83(&betay[index]);\n"
  "      PDupwindNthAnti1betay = PDupwindNthAntifdOrder81(&betay[index]);\n"
  "      PDupwindNthAnti2betay = PDupwindNthAntifdOrder82(&betay[index]);\n"
  "      PDupwindNthAnti3betay = PDupwindNthAntifdOrder83(&betay[index]);\n"
  "      PDupwindNthSymm1betaz = PDupwindNthSymmfdOrder81(&betaz[index]);\n"
  "      PDupwindNthSymm2betaz = PDupwindNthSymmfdOrder82(&betaz[index]);\n"
  "      PDupwindNthSymm3betaz = PDupwindNthSymmfdOrder83(&betaz[index]);\n"
  "      PDupwindNthAnti1betaz = PDupwindNthAntifdOrder81(&betaz[index]);\n"
  "      PDupwindNthAnti2betaz = PDupwindNthAntifdOrder82(&betaz[index]);\n"
  "      PDupwindNthAnti3betaz = PDupwindNthAntifdOrder83(&betaz[index]);\n"
  "      PDstandardNth1gt11 = PDstandardNthfdOrder81(&gt11[index]);\n"
  "      PDstandardNth2gt11 = PDstandardNthfdOrder82(&gt11[index]);\n"
  "      PDstandardNth3gt11 = PDstandardNthfdOrder83(&gt11[index]);\n"
  "      PDstandardNth1gt12 = PDstandardNthfdOrder81(&gt12[index]);\n"
  "      PDstandardNth2gt12 = PDstandardNthfdOrder82(&gt12[index]);\n"
  "      PDstandardNth3gt12 = PDstandardNthfdOrder83(&gt12[index]);\n"
  "      PDstandardNth1gt13 = PDstandardNthfdOrder81(&gt13[index]);\n"
  "      PDstandardNth2gt13 = PDstandardNthfdOrder82(&gt13[index]);\n"
  "      PDstandardNth3gt13 = PDstandardNthfdOrder83(&gt13[index]);\n"
  "      PDstandardNth1gt22 = PDstandardNthfdOrder81(&gt22[index]);\n"
  "      PDstandardNth2gt22 = PDstandardNthfdOrder82(&gt22[index]);\n"
  "      PDstandardNth3gt22 = PDstandardNthfdOrder83(&gt22[index]);\n"
  "      PDstandardNth1gt23 = PDstandardNthfdOrder81(&gt23[index]);\n"
  "      PDstandardNth2gt23 = PDstandardNthfdOrder82(&gt23[index]);\n"
  "      PDstandardNth3gt23 = PDstandardNthfdOrder83(&gt23[index]);\n"
  "      PDstandardNth1gt33 = PDstandardNthfdOrder81(&gt33[index]);\n"
  "      PDstandardNth2gt33 = PDstandardNthfdOrder82(&gt33[index]);\n"
  "      PDstandardNth3gt33 = PDstandardNthfdOrder83(&gt33[index]);\n"
  "      break;\n"
  "    }\n"
  "    default:\n"
  "      CCTK_BUILTIN_UNREACHABLE();\n"
  "  }\n"
  "  /* Calculate temporaries and grid functions */\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth1gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth2gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt11 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt12 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt13 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt22 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt23 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDstandardNth3gt33 CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti1alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti1betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti1betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti1betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti2alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti2betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti2betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti2betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti3alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti3betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti3betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthAnti3betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm1alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm1betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm1betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm1betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm2alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm2betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm2betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm2betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm3alp CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm3betax CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm3betay CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC JacPDupwindNthSymm3betaz CCTK_ATTRIBUTE_UNUSED;\n"
  "  \n"
  "  if (usejacobian)\n"
  "  {\n"
  "    JacPDstandardNth1gt11 = \n"
  "      kmadd(J11L,PDstandardNth1gt11,kmadd(J21L,PDstandardNth2gt11,kmul(J31L,PDstandardNth3gt11)));\n"
  "    \n"
  "    JacPDstandardNth1gt12 = \n"
  "      kmadd(J11L,PDstandardNth1gt12,kmadd(J21L,PDstandardNth2gt12,kmul(J31L,PDstandardNth3gt12)));\n"
  "    \n"
  "    JacPDstandardNth1gt13 = \n"
  "      kmadd(J11L,PDstandardNth1gt13,kmadd(J21L,PDstandardNth2gt13,kmul(J31L,PDstandardNth3gt13)));\n"
  "    \n"
  "    JacPDstandardNth1gt22 = \n"
  "      kmadd(J11L,PDstandardNth1gt22,kmadd(J21L,PDstandardNth2gt22,kmul(J31L,PDstandardNth3gt22)));\n"
  "    \n"
  "    JacPDstandardNth1gt23 = \n"
  "      kmadd(J11L,PDstandardNth1gt23,kmadd(J21L,PDstandardNth2gt23,kmul(J31L,PDstandardNth3gt23)));\n"
  "    \n"
  "    JacPDstandardNth1gt33 = \n"
  "      kmadd(J11L,PDstandardNth1gt33,kmadd(J21L,PDstandardNth2gt33,kmul(J31L,PDstandardNth3gt33)));\n"
  "    \n"
  "    JacPDstandardNth2gt11 = \n"
  "      kmadd(J12L,PDstandardNth1gt11,kmadd(J22L,PDstandardNth2gt11,kmul(J32L,PDstandardNth3gt11)));\n"
  "    \n"
  "    JacPDstandardNth2gt12 = \n"
  "      kmadd(J12L,PDstandardNth1gt12,kmadd(J22L,PDstandardNth2gt12,kmul(J32L,PDstandardNth3gt12)));\n"
  "    \n"
  "    JacPDstandardNth2gt13 = \n"
  "      kmadd(J12L,PDstandardNth1gt13,kmadd(J22L,PDstandardNth2gt13,kmul(J32L,PDstandardNth3gt13)));\n"
  "    \n"
  "    JacPDstandardNth2gt22 = \n"
  "      kmadd(J12L,PDstandardNth1gt22,kmadd(J22L,PDstandardNth2gt22,kmul(J32L,PDstandardNth3gt22)));\n"
  "    \n"
  "    JacPDstandardNth2gt23 = \n"
  "      kmadd(J12L,PDstandardNth1gt23,kmadd(J22L,PDstandardNth2gt23,kmul(J32L,PDstandardNth3gt23)));\n"
  "    \n"
  "    JacPDstandardNth2gt33 = \n"
  "      kmadd(J12L,PDstandardNth1gt33,kmadd(J22L,PDstandardNth2gt33,kmul(J32L,PDstandardNth3gt33)));\n"
  "    \n"
  "    JacPDstandardNth3gt11 = \n"
  "      kmadd(J13L,PDstandardNth1gt11,kmadd(J23L,PDstandardNth2gt11,kmul(J33L,PDstandardNth3gt11)));\n"
  "    \n"
  "    JacPDstandardNth3gt12 = \n"
  "      kmadd(J13L,PDstandardNth1gt12,kmadd(J23L,PDstandardNth2gt12,kmul(J33L,PDstandardNth3gt12)));\n"
  "    \n"
  "    JacPDstandardNth3gt13 = \n"
  "      kmadd(J13L,PDstandardNth1gt13,kmadd(J23L,PDstandardNth2gt13,kmul(J33L,PDstandardNth3gt13)));\n"
  "    \n"
  "    JacPDstandardNth3gt22 = \n"
  "      kmadd(J13L,PDstandardNth1gt22,kmadd(J23L,PDstandardNth2gt22,kmul(J33L,PDstandardNth3gt22)));\n"
  "    \n"
  "    JacPDstandardNth3gt23 = \n"
  "      kmadd(J13L,PDstandardNth1gt23,kmadd(J23L,PDstandardNth2gt23,kmul(J33L,PDstandardNth3gt23)));\n"
  "    \n"
  "    JacPDstandardNth3gt33 = \n"
  "      kmadd(J13L,PDstandardNth1gt33,kmadd(J23L,PDstandardNth2gt33,kmul(J33L,PDstandardNth3gt33)));\n"
  "    \n"
  "    JacPDupwindNthSymm1alp = \n"
  "      kmadd(J11L,PDupwindNthSymm1alp,kmadd(J21L,PDupwindNthSymm2alp,kmul(J31L,PDupwindNthSymm3alp)));\n"
  "    \n"
  "    JacPDupwindNthSymm1betax = \n"
  "      kmadd(J11L,PDupwindNthSymm1betax,kmadd(J21L,PDupwindNthSymm2betax,kmul(J31L,PDupwindNthSymm3betax)));\n"
  "    \n"
  "    JacPDupwindNthSymm1betay = \n"
  "      kmadd(J11L,PDupwindNthSymm1betay,kmadd(J21L,PDupwindNthSymm2betay,kmul(J31L,PDupwindNthSymm3betay)));\n"
  "    \n"
  "    JacPDupwindNthSymm1betaz = \n"
  "      kmadd(J11L,PDupwindNthSymm1betaz,kmadd(J21L,PDupwindNthSymm2betaz,kmul(J31L,PDupwindNthSymm3betaz)));\n"
  "    \n"
  "    JacPDupwindNthSymm2alp = \n"
  "      kmadd(J12L,PDupwindNthSymm1alp,kmadd(J22L,PDupwindNthSymm2alp,kmul(J32L,PDupwindNthSymm3alp)));\n"
  "    \n"
  "    JacPDupwindNthSymm2betax = \n"
  "      kmadd(J12L,PDupwindNthSymm1betax,kmadd(J22L,PDupwindNthSymm2betax,kmul(J32L,PDupwindNthSymm3betax)));\n"
  "    \n"
  "    JacPDupwindNthSymm2betay = \n"
  "      kmadd(J12L,PDupwindNthSymm1betay,kmadd(J22L,PDupwindNthSymm2betay,kmul(J32L,PDupwindNthSymm3betay)));\n"
  "    \n"
  "    JacPDupwindNthSymm2betaz = \n"
  "      kmadd(J12L,PDupwindNthSymm1betaz,kmadd(J22L,PDupwindNthSymm2betaz,kmul(J32L,PDupwindNthSymm3betaz)));\n"
  "    \n"
  "    JacPDupwindNthSymm3alp = \n"
  "      kmadd(J13L,PDupwindNthSymm1alp,kmadd(J23L,PDupwindNthSymm2alp,kmul(J33L,PDupwindNthSymm3alp)));\n"
  "    \n"
  "    JacPDupwindNthSymm3betax = \n"
  "      kmadd(J13L,PDupwindNthSymm1betax,kmadd(J23L,PDupwindNthSymm2betax,kmul(J33L,PDupwindNthSymm3betax)));\n"
  "    \n"
  "    JacPDupwindNthSymm3betay = \n"
  "      kmadd(J13L,PDupwindNthSymm1betay,kmadd(J23L,PDupwindNthSymm2betay,kmul(J33L,PDupwindNthSymm3betay)));\n"
  "    \n"
  "    JacPDupwindNthSymm3betaz = \n"
  "      kmadd(J13L,PDupwindNthSymm1betaz,kmadd(J23L,PDupwindNthSymm2betaz,kmul(J33L,PDupwindNthSymm3betaz)));\n"
  "    \n"
  "    JacPDupwindNthAnti1alp = \n"
  "      kmadd(J11L,PDupwindNthAnti1alp,kmadd(J21L,PDupwindNthAnti2alp,kmul(J31L,PDupwindNthAnti3alp)));\n"
  "    \n"
  "    JacPDupwindNthAnti1betax = \n"
  "      kmadd(J11L,PDupwindNthAnti1betax,kmadd(J21L,PDupwindNthAnti2betax,kmul(J31L,PDupwindNthAnti3betax)));\n"
  "    \n"
  "    JacPDupwindNthAnti1betay = \n"
  "      kmadd(J11L,PDupwindNthAnti1betay,kmadd(J21L,PDupwindNthAnti2betay,kmul(J31L,PDupwindNthAnti3betay)));\n"
  "    \n"
  "    JacPDupwindNthAnti1betaz = \n"
  "      kmadd(J11L,PDupwindNthAnti1betaz,kmadd(J21L,PDupwindNthAnti2betaz,kmul(J31L,PDupwindNthAnti3betaz)));\n"
  "    \n"
  "    JacPDupwindNthAnti2alp = \n"
  "      kmadd(J12L,PDupwindNthAnti1alp,kmadd(J22L,PDupwindNthAnti2alp,kmul(J32L,PDupwindNthAnti3alp)));\n"
  "    \n"
  "    JacPDupwindNthAnti2betax = \n"
  "      kmadd(J12L,PDupwindNthAnti1betax,kmadd(J22L,PDupwindNthAnti2betax,kmul(J32L,PDupwindNthAnti3betax)));\n"
  "    \n"
  "    JacPDupwindNthAnti2betay = \n"
  "      kmadd(J12L,PDupwindNthAnti1betay,kmadd(J22L,PDupwindNthAnti2betay,kmul(J32L,PDupwindNthAnti3betay)));\n"
  "    \n"
  "    JacPDupwindNthAnti2betaz = \n"
  "      kmadd(J12L,PDupwindNthAnti1betaz,kmadd(J22L,PDupwindNthAnti2betaz,kmul(J32L,PDupwindNthAnti3betaz)));\n"
  "    \n"
  "    JacPDupwindNthAnti3alp = \n"
  "      kmadd(J13L,PDupwindNthAnti1alp,kmadd(J23L,PDupwindNthAnti2alp,kmul(J33L,PDupwindNthAnti3alp)));\n"
  "    \n"
  "    JacPDupwindNthAnti3betax = \n"
  "      kmadd(J13L,PDupwindNthAnti1betax,kmadd(J23L,PDupwindNthAnti2betax,kmul(J33L,PDupwindNthAnti3betax)));\n"
  "    \n"
  "    JacPDupwindNthAnti3betay = \n"
  "      kmadd(J13L,PDupwindNthAnti1betay,kmadd(J23L,PDupwindNthAnti2betay,kmul(J33L,PDupwindNthAnti3betay)));\n"
  "    \n"
  "    JacPDupwindNthAnti3betaz = \n"
  "      kmadd(J13L,PDupwindNthAnti1betaz,kmadd(J23L,PDupwindNthAnti2betaz,kmul(J33L,PDupwindNthAnti3betaz)));\n"
  "  }\n"
  "  else\n"
  "  {\n"
  "    JacPDstandardNth1gt11 = PDstandardNth1gt11;\n"
  "    \n"
  "    JacPDstandardNth1gt12 = PDstandardNth1gt12;\n"
  "    \n"
  "    JacPDstandardNth1gt13 = PDstandardNth1gt13;\n"
  "    \n"
  "    JacPDstandardNth1gt22 = PDstandardNth1gt22;\n"
  "    \n"
  "    JacPDstandardNth1gt23 = PDstandardNth1gt23;\n"
  "    \n"
  "    JacPDstandardNth1gt33 = PDstandardNth1gt33;\n"
  "    \n"
  "    JacPDstandardNth2gt11 = PDstandardNth2gt11;\n"
  "    \n"
  "    JacPDstandardNth2gt12 = PDstandardNth2gt12;\n"
  "    \n"
  "    JacPDstandardNth2gt13 = PDstandardNth2gt13;\n"
  "    \n"
  "    JacPDstandardNth2gt22 = PDstandardNth2gt22;\n"
  "    \n"
  "    JacPDstandardNth2gt23 = PDstandardNth2gt23;\n"
  "    \n"
  "    JacPDstandardNth2gt33 = PDstandardNth2gt33;\n"
  "    \n"
  "    JacPDstandardNth3gt11 = PDstandardNth3gt11;\n"
  "    \n"
  "    JacPDstandardNth3gt12 = PDstandardNth3gt12;\n"
  "    \n"
  "    JacPDstandardNth3gt13 = PDstandardNth3gt13;\n"
  "    \n"
  "    JacPDstandardNth3gt22 = PDstandardNth3gt22;\n"
  "    \n"
  "    JacPDstandardNth3gt23 = PDstandardNth3gt23;\n"
  "    \n"
  "    JacPDstandardNth3gt33 = PDstandardNth3gt33;\n"
  "    \n"
  "    JacPDupwindNthSymm1alp = PDupwindNthSymm1alp;\n"
  "    \n"
  "    JacPDupwindNthSymm1betax = PDupwindNthSymm1betax;\n"
  "    \n"
  "    JacPDupwindNthSymm1betay = PDupwindNthSymm1betay;\n"
  "    \n"
  "    JacPDupwindNthSymm1betaz = PDupwindNthSymm1betaz;\n"
  "    \n"
  "    JacPDupwindNthSymm2alp = PDupwindNthSymm2alp;\n"
  "    \n"
  "    JacPDupwindNthSymm2betax = PDupwindNthSymm2betax;\n"
  "    \n"
  "    JacPDupwindNthSymm2betay = PDupwindNthSymm2betay;\n"
  "    \n"
  "    JacPDupwindNthSymm2betaz = PDupwindNthSymm2betaz;\n"
  "    \n"
  "    JacPDupwindNthSymm3alp = PDupwindNthSymm3alp;\n"
  "    \n"
  "    JacPDupwindNthSymm3betax = PDupwindNthSymm3betax;\n"
  "    \n"
  "    JacPDupwindNthSymm3betay = PDupwindNthSymm3betay;\n"
  "    \n"
  "    JacPDupwindNthSymm3betaz = PDupwindNthSymm3betaz;\n"
  "    \n"
  "    JacPDupwindNthAnti1alp = PDupwindNthAnti1alp;\n"
  "    \n"
  "    JacPDupwindNthAnti1betax = PDupwindNthAnti1betax;\n"
  "    \n"
  "    JacPDupwindNthAnti1betay = PDupwindNthAnti1betay;\n"
  "    \n"
  "    JacPDupwindNthAnti1betaz = PDupwindNthAnti1betaz;\n"
  "    \n"
  "    JacPDupwindNthAnti2alp = PDupwindNthAnti2alp;\n"
  "    \n"
  "    JacPDupwindNthAnti2betax = PDupwindNthAnti2betax;\n"
  "    \n"
  "    JacPDupwindNthAnti2betay = PDupwindNthAnti2betay;\n"
  "    \n"
  "    JacPDupwindNthAnti2betaz = PDupwindNthAnti2betaz;\n"
  "    \n"
  "    JacPDupwindNthAnti3alp = PDupwindNthAnti3alp;\n"
  "    \n"
  "    JacPDupwindNthAnti3betax = PDupwindNthAnti3betax;\n"
  "    \n"
  "    JacPDupwindNthAnti3betay = PDupwindNthAnti3betay;\n"
  "    \n"
  "    JacPDupwindNthAnti3betaz = PDupwindNthAnti3betaz;\n"
  "  }\n"
  "  \n"
  "  CCTK_REAL_VEC g11 CCTK_ATTRIBUTE_UNUSED = gxxL;\n"
  "  \n"
  "  CCTK_REAL_VEC g12 CCTK_ATTRIBUTE_UNUSED = gxyL;\n"
  "  \n"
  "  CCTK_REAL_VEC g13 CCTK_ATTRIBUTE_UNUSED = gxzL;\n"
  "  \n"
  "  CCTK_REAL_VEC g22 CCTK_ATTRIBUTE_UNUSED = gyyL;\n"
  "  \n"
  "  CCTK_REAL_VEC g23 CCTK_ATTRIBUTE_UNUSED = gyzL;\n"
  "  \n"
  "  CCTK_REAL_VEC g33 CCTK_ATTRIBUTE_UNUSED = gzzL;\n"
  "  \n"
  "  CCTK_REAL_VEC detg CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmadd(ToReal(2),kmul(g12,kmul(g13,g23)),knmsub(g33,kmul(g12,g12),kmsub(g22,kmsub(g11,g33,kmul(g13,g13)),kmul(g11,kmul(g23,g23)))));\n"
  "  \n"
  "  CCTK_REAL_VEC gu11 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g22,g33,kmul(g23,g23)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC gu12 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g13,g23,kmul(g12,g33)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC gu13 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g12,g23,kmul(g13,g22)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC gu22 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g11,g33,kmul(g13,g13)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC gu23 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g12,g13,kmul(g11,g23)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC gu33 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kdiv(kmsub(g11,g22,kmul(g12,g12)),detg);\n"
  "  \n"
  "  CCTK_REAL_VEC em4phi CCTK_ATTRIBUTE_UNUSED = IfThen(conformalMethod != \n"
  "    0,kmul(phiL,phiL),kexp(kmul(phiL,ToReal(-4))));\n"
  "  \n"
  "  CCTK_REAL_VEC gtu11 CCTK_ATTRIBUTE_UNUSED = kdiv(gu11,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC gtu12 CCTK_ATTRIBUTE_UNUSED = kdiv(gu12,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC gtu13 CCTK_ATTRIBUTE_UNUSED = kdiv(gu13,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC gtu22 CCTK_ATTRIBUTE_UNUSED = kdiv(gu22,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC gtu23 CCTK_ATTRIBUTE_UNUSED = kdiv(gu23,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC gtu33 CCTK_ATTRIBUTE_UNUSED = kdiv(gu33,em4phi);\n"
  "  \n"
  "  CCTK_REAL_VEC Gt111 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu11,JacPDstandardNth1gt11,kmsub(ToReal(2),kmadd(gtu12,JacPDstandardNth1gt12,kmul(gtu13,JacPDstandardNth1gt13)),kmadd(gtu13,JacPDstandardNth3gt11,kmul(gtu12,JacPDstandardNth2gt11)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt211 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu12,JacPDstandardNth1gt11,kmsub(ToReal(2),kmadd(gtu22,JacPDstandardNth1gt12,kmul(gtu23,JacPDstandardNth1gt13)),kmadd(gtu23,JacPDstandardNth3gt11,kmul(gtu22,JacPDstandardNth2gt11)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt311 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu13,JacPDstandardNth1gt11,kmsub(ToReal(2),kmadd(gtu23,JacPDstandardNth1gt12,kmul(gtu33,JacPDstandardNth1gt13)),kmadd(gtu33,JacPDstandardNth3gt11,kmul(gtu23,JacPDstandardNth2gt11)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt112 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu12,JacPDstandardNth1gt22,kmadd(gtu11,JacPDstandardNth2gt11,kmul(gtu13,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth2gt13,JacPDstandardNth3gt12))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt212 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu22,JacPDstandardNth1gt22,kmadd(gtu12,JacPDstandardNth2gt11,kmul(gtu23,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth2gt13,JacPDstandardNth3gt12))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt312 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu23,JacPDstandardNth1gt22,kmadd(gtu13,JacPDstandardNth2gt11,kmul(gtu33,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth2gt13,JacPDstandardNth3gt12))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt113 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu13,JacPDstandardNth1gt33,kmadd(gtu11,JacPDstandardNth3gt11,kmul(gtu12,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth3gt12,JacPDstandardNth2gt13))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt213 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu23,JacPDstandardNth1gt33,kmadd(gtu12,JacPDstandardNth3gt11,kmul(gtu22,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth3gt12,JacPDstandardNth2gt13))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt313 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu33,JacPDstandardNth1gt33,kmadd(gtu13,JacPDstandardNth3gt11,kmul(gtu23,kadd(JacPDstandardNth1gt23,ksub(JacPDstandardNth3gt12,JacPDstandardNth2gt13))))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt122 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu11,kmsub(ToReal(2),JacPDstandardNth2gt12,JacPDstandardNth1gt22),kmadd(gtu12,JacPDstandardNth2gt22,kmul(gtu13,kmsub(ToReal(2),JacPDstandardNth2gt23,JacPDstandardNth3gt22)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt222 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu12,kmsub(ToReal(2),JacPDstandardNth2gt12,JacPDstandardNth1gt22),kmadd(gtu22,JacPDstandardNth2gt22,kmul(gtu23,kmsub(ToReal(2),JacPDstandardNth2gt23,JacPDstandardNth3gt22)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt322 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu13,kmsub(ToReal(2),JacPDstandardNth2gt12,JacPDstandardNth1gt22),kmadd(gtu23,JacPDstandardNth2gt22,kmul(gtu33,kmsub(ToReal(2),JacPDstandardNth2gt23,JacPDstandardNth3gt22)))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt123 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu13,JacPDstandardNth2gt33,kmadd(gtu11,ksub(kadd(JacPDstandardNth2gt13,JacPDstandardNth3gt12),JacPDstandardNth1gt23),kmul(gtu12,JacPDstandardNth3gt22))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt223 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu23,JacPDstandardNth2gt33,kmadd(gtu12,ksub(kadd(JacPDstandardNth2gt13,JacPDstandardNth3gt12),JacPDstandardNth1gt23),kmul(gtu22,JacPDstandardNth3gt22))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt323 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu33,JacPDstandardNth2gt33,kmadd(gtu13,ksub(kadd(JacPDstandardNth2gt13,JacPDstandardNth3gt12),JacPDstandardNth1gt23),kmul(gtu23,JacPDstandardNth3gt22))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt133 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu11,kmsub(ToReal(2),JacPDstandardNth3gt13,JacPDstandardNth1gt33),kmadd(gtu12,kmsub(ToReal(2),JacPDstandardNth3gt23,JacPDstandardNth2gt33),kmul(gtu13,JacPDstandardNth3gt33))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt233 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu12,kmsub(ToReal(2),JacPDstandardNth3gt13,JacPDstandardNth1gt33),kmadd(gtu22,kmsub(ToReal(2),JacPDstandardNth3gt23,JacPDstandardNth2gt33),kmul(gtu23,JacPDstandardNth3gt33))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Gt333 CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmul(kmadd(gtu13,kmsub(ToReal(2),JacPDstandardNth3gt13,JacPDstandardNth1gt33),kmadd(gtu23,kmsub(ToReal(2),JacPDstandardNth3gt23,JacPDstandardNth2gt33),kmul(gtu33,JacPDstandardNth3gt33))),ToReal(0.5));\n"
  "  \n"
  "  CCTK_REAL_VEC Xt1L CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmadd(Gt111,gtu11,kmadd(Gt122,gtu22,kmadd(ToReal(2),kmadd(Gt112,gtu12,kmadd(Gt113,gtu13,kmul(Gt123,gtu23))),kmul(Gt133,gtu33))));\n"
  "  \n"
  "  CCTK_REAL_VEC Xt2L CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmadd(Gt211,gtu11,kmadd(Gt222,gtu22,kmadd(ToReal(2),kmadd(Gt212,gtu12,kmadd(Gt213,gtu13,kmul(Gt223,gtu23))),kmul(Gt233,gtu33))));\n"
  "  \n"
  "  CCTK_REAL_VEC Xt3L CCTK_ATTRIBUTE_UNUSED = \n"
  "    kmadd(Gt311,gtu11,kmadd(Gt322,gtu22,kmadd(ToReal(2),kmadd(Gt312,gtu12,kmadd(Gt313,gtu13,kmul(Gt323,gtu23))),kmul(Gt333,gtu33))));\n"
  "  \n"
  "  CCTK_REAL_VEC AL CCTK_ATTRIBUTE_UNUSED = IfThen(evolveA != \n"
  "    0,kmul(kmul(ksub(IfThen(advectLapse != \n"
  "    0,kmadd(betaxL,JacPDupwindNthAnti1alp,kmadd(betayL,JacPDupwindNthAnti2alp,kmadd(betazL,JacPDupwindNthAnti3alp,kmadd(JacPDupwindNthSymm1alp,kfabs(betaxL),kmadd(JacPDupwindNthSymm2alp,kfabs(betayL),kmul(JacPDupwindNthSymm3alp,kfabs(betazL))))))),ToReal(0)),dtalpL),kpow(alpL,-harmonicN)),ToReal(pow(harmonicF,-1))),ToReal(0));\n"
  "  \n"
  "  CCTK_REAL_VEC shiftGammaCoeffValue CCTK_ATTRIBUTE_UNUSED = \n"
  "    IfThen(useSpatialShiftGammaCoeff != \n"
  "    0,kmul(kfmin(ToReal(1),kexp(knmsub(ToReal(pow(spatialShiftGammaCoeffRadius,-1)),rL,ToReal(1)))),ToReal(shiftGammaCoeff)),ToReal(shiftGammaCoeff));\n"
  "  \n"
  "  CCTK_REAL_VEC B1L CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC B2L CCTK_ATTRIBUTE_UNUSED;\n"
  "  CCTK_REAL_VEC B3L CCTK_ATTRIBUTE_UNUSED;\n"
  "  \n"
  "  if (evolveB != 0)\n"
  "  {\n"
  "    B1L = \n"
  "      kdiv(kmul(kpow(alpL,-shiftAlphaPower),ksub(dtbetaxL,IfThen(advectShift \n"
  "      != \n"
  "      0,kmadd(betaxL,JacPDupwindNthAnti1betax,kmadd(betayL,JacPDupwindNthAnti2betax,kmadd(betazL,JacPDupwindNthAnti3betax,kmadd(JacPDupwindNthSymm1betax,kfabs(betaxL),kmadd(JacPDupwindNthSymm2betax,kfabs(betayL),kmul(JacPDupwindNthSymm3betax,kfabs(betazL))))))),ToReal(0)))),shiftGammaCoeffValue);\n"
  "    \n"
  "    B2L = \n"
  "      kdiv(kmul(kpow(alpL,-shiftAlphaPower),ksub(dtbetayL,IfThen(advectShift \n"
  "      != \n"
  "      0,kmadd(betaxL,JacPDupwindNthAnti1betay,kmadd(betayL,JacPDupwindNthAnti2betay,kmadd(betazL,JacPDupwindNthAnti3betay,kmadd(JacPDupwindNthSymm1betay,kfabs(betaxL),kmadd(JacPDupwindNthSymm2betay,kfabs(betayL),kmul(JacPDupwindNthSymm3betay,kfabs(betazL))))))),ToReal(0)))),shiftGammaCoeffValue);\n"
  "    \n"
  "    B3L = \n"
  "      kdiv(kmul(kpow(alpL,-shiftAlphaPower),ksub(dtbetazL,IfThen(advectShift \n"
  "      != \n"
  "      0,kmadd(betaxL,JacPDupwindNthAnti1betaz,kmadd(betayL,JacPDupwindNthAnti2betaz,kmadd(betazL,JacPDupwindNthAnti3betaz,kmadd(JacPDupwindNthSymm1betaz,kfabs(betaxL),kmadd(JacPDupwindNthSymm2betaz,kfabs(betayL),kmul(JacPDupwindNthSymm3betaz,kfabs(betazL))))))),ToReal(0)))),shiftGammaCoeffValue);\n"
  "  }\n"
  "  else\n"
  "  {\n"
  "    B1L = ToReal(0);\n"
  "    \n"
  "    B2L = ToReal(0);\n"
  "    \n"
  "    B3L = ToReal(0);\n"
  "  }\n"
  "  /* Copy local copies back to grid functions */\n"
  "  vec_store_partial_prepare(i,lc_imin,lc_imax);\n"
  "  vec_store_nta_partial(A[index],AL);\n"
  "  vec_store_nta_partial(B1[index],B1L);\n"
  "  vec_store_nta_partial(B2[index],B2L);\n"
  "  vec_store_nta_partial(B3[index],B3L);\n"
  "  vec_store_nta_partial(Xt1[index],Xt1L);\n"
  "  vec_store_nta_partial(Xt2[index],Xt2L);\n"
  "  vec_store_nta_partial(Xt3[index],Xt3L);\n"
  "}\n"
  "CCTK_ENDLOOP3STR(ML_BSSN_CL_InitialADMBase2Interior);\n"
  ""
  ;
  
  const char* const groups[] = {
    "ADMBase::dtlapse",
    "ADMBase::dtshift",
    "ADMBase::lapse",
    "ADMBase::metric",
    "ADMBase::shift",
    "grid::coordinates",
    "ML_BSSN_CL::ML_dtlapse",
    "ML_BSSN_CL::ML_dtshift",
    "ML_BSSN_CL::ML_Gamma",
    "ML_BSSN_CL::ML_log_confac",
    "ML_BSSN_CL::ML_metric",
    NULL};
  
  static struct OpenCLKernel *kernel = NULL;
  const char* const sources[] = {differencing, source, NULL};
  OpenCLRunTime_CallKernel(cctkGH, CCTK_THORNSTRING, "ML_BSSN_CL_InitialADMBase2Interior",
                           sources, groups, NULL, NULL, NULL, -1,
                           imin, imax, &kernel);
  
}
extern "C" void ML_BSSN_CL_InitialADMBase2Interior(CCTK_ARGUMENTS)
{
  #ifdef DECLARE_CCTK_ARGUMENTS_ML_BSSN_CL_InitialADMBase2Interior
  DECLARE_CCTK_ARGUMENTS_CHECKED(ML_BSSN_CL_InitialADMBase2Interior);
  #else
  DECLARE_CCTK_ARGUMENTS;
  #endif
  DECLARE_CCTK_PARAMETERS;
  
  if (verbose > 1)
  {
    CCTK_VInfo(CCTK_THORNSTRING,"Entering ML_BSSN_CL_InitialADMBase2Interior_Body");
  }
  if (cctk_iteration % ML_BSSN_CL_InitialADMBase2Interior_calc_every != ML_BSSN_CL_InitialADMBase2Interior_calc_offset)
  {
    return;
  }
  
  const char* const groups[] = {
    "ADMBase::dtlapse",
    "ADMBase::dtshift",
    "ADMBase::lapse",
    "ADMBase::metric",
    "ADMBase::shift",
    "grid::coordinates",
    "ML_BSSN_CL::ML_dtlapse",
    "ML_BSSN_CL::ML_dtshift",
    "ML_BSSN_CL::ML_Gamma",
    "ML_BSSN_CL::ML_log_confac",
    "ML_BSSN_CL::ML_metric"};
  AssertGroupStorage(cctkGH, "ML_BSSN_CL_InitialADMBase2Interior", 11, groups);
  
  switch (fdOrder)
  {
    case 2:
    {
      EnsureStencilFits(cctkGH, "ML_BSSN_CL_InitialADMBase2Interior", 2, 2, 2);
      break;
    }
    
    case 4:
    {
      EnsureStencilFits(cctkGH, "ML_BSSN_CL_InitialADMBase2Interior", 3, 3, 3);
      break;
    }
    
    case 6:
    {
      EnsureStencilFits(cctkGH, "ML_BSSN_CL_InitialADMBase2Interior", 4, 4, 4);
      break;
    }
    
    case 8:
    {
      EnsureStencilFits(cctkGH, "ML_BSSN_CL_InitialADMBase2Interior", 5, 5, 5);
      break;
    }
    default:
      CCTK_BUILTIN_UNREACHABLE();
  }
  
  LoopOverInterior(cctkGH, ML_BSSN_CL_InitialADMBase2Interior_Body);
  if (verbose > 1)
  {
    CCTK_VInfo(CCTK_THORNSTRING,"Leaving ML_BSSN_CL_InitialADMBase2Interior_Body");
  }
}

} // namespace ML_BSSN_CL
